# @author Jesutofunmi Kupoluyi
# @brief Makefile for the aesdsocket.c source file
# @date: 19 June, 2023

TARGET = aesdsocket

all:
	$(CROSS_COMPILE)gcc $(TARGET).c -o $(TARGET)

default: all

clean:
	rm $(TARGET)
